{
 "title": "Reddit Sentiments",
 "time": { "from": "2025-03-29T01:24:08.492Z", "to": "2025-03-30T00:59:44.554Z" },
 "panels": [
  {
   "title": "Text Sentiment Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"my-test-bucket\")\r\n  |> range(start: -1w)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reddit_sentiment\" and r[\"_field\"] == \"text_sentiment\")\r\n"
    }
   ]
  },
  {
   "title": "Title Sentiment Distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"my-test-bucket\")\r\n  |> range(start: -1w)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reddit_sentiment\" and r[\"_field\"] == \"title_sentiment\")\r\n  "
    }
   ]
  },
  {
   "title": "Average Text Sentiment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"my-test-bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reddit_sentiment\" and r[\"_field\"] == \"text_sentiment\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"Average Text Sentiment\")"
    }
   ]
  },
  {
   "title": "Average Title Sentiment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"my-test-bucket\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"reddit_sentiment\" and r[\"_field\"] == \"title_sentiment\")\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n  |> yield(name: \"Average Title Sentiment\")"
    }
   ]
  }
 ]
}